### ISSUE TITLE
MAP Failure: column i._cable_peer_id does not exist LINE 27: ON 

### ISSUE THREAD

**Issue by LHBL2003** [den-it/ntmap#14]
NTMAP v0.7.1
NETBOX v3.2.2
Python 3.10.4
PostgreSQL 14.2
Ubuntu 14.2

No matter which device I write into the Shema, I always get this error message.
Even if I enter a switch and a server that are connected, I get this error message.

column i._cable_peer_id does not exist LINE 27: ON (ni.id = i._cable_peer_id... ^

<img width="500" alt="2022-05-19_10h41_41" src="https://user-images.githubusercontent.com/46369917/169251669-5e9a709b-3a6f-4001-add1-8704dbf2b86d.png">

<img width="942" alt="image" src="https://user-images.githubusercontent.com/46369917/169251812-f0cc9f83-0d56-41d2-b51d-4c6eae0bbdcf.png">

**Comment by LHBL2003** [comment]
Due to error column "_cable_peer_id" is not present by name in the dcim_interface.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/46369917/169282381-feb25b76-3afd-4fd7-bdc9-8737d356a60d.png">

**Comment by LHBL2003** [comment]
Two columns were renamed. (21 Oct 2021)

https://github.com/netbox-community/netbox/blob/f94c1e91ea20c805528125407193371476ccbcd8/netbox/circuits/migrations/0004_rename_cable_peer.py

_cable_peer_id --> _link_peer_id
_cable_peer_type --> _link_peer_type

And this must also be adapted

_cable_peer_type_id --> _link_peer_type_id

Then it also works in the current version

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/46369917/169285634-1583f956-9b5b-4fd1-b49f-3c2e55f3fce1.png">

**Comment by den-it** [comment]
Fixed in v0.8.0
