### ISSUE TITLE
Dynamic enable/disable for devices on map

### ISSUE THREAD

**Issue by denisvorlov** [den-it/ntmap#4]
Hi
When the number of devices on the map topology is large, it would be useful to have a panel with a list of devices, where opposite each device would be checkbox, which would allow you to adjust the display/hide of the device on the topology map.

**Comment by den-it** [comment]
It seems like this is a duplicated function. Ntmap already has filters for displayed devices. When you define a map you define a query string for searching devices in Netbox. This is actually the display filter. Having another filter will make the "filter over filter" situation which seems to be an overkill.

What I am thinking about is some grouping of devices and expand/collapse function for groups. Just the same behaviour as virtual chassis memebers have. It can be apllied to devices that have different control plane, but the same functionality in the network. Like all spine switches or all leaf switches of a CLOS-fabric.

Currently not sure what data structures to use in Netbox for device grouping. Vanilla Netbox doesn't have an explicit object for this (like it has structures for VC and clusters).
