### ISSUE TITLE
NetBox v3.0 Support

### ISSUE THREAD

**Issue by ryanmerolle** [den-it/ntmap#7]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by hiddenman** [comment]
Hi,
Yes, please, update.

**Comment by den-it** [comment]
I've tested Ntmap 0.7.1 with latest Netbox 3.0.1. It seems to be that Ntmap still works good as a separate application, not a plugin. No changes to Ntmap code are necessary to support the latest Netbox release. 

May be, I just don't see the reason to change Ntmap architecture. Please, provide additional details if you still need this .

**Comment by ryanmerolle** [comment]
Most plugins are built in to netbox and need to make changes to support the update.  If that is not the case, feel free to close this issue.  This issue was just a courtesy communication given the major update.

**Comment by ryanmerolle** [comment]
Ah!  Apologies I thought this was a netbox plugin hence the topic netbox_plugin that you applied to this GitHub project.  Plugins are set by adding to the netbox config.py.  Plugins required a minor update to support netbox 3.0.  NetBox maintainers we’re trying to get ahead of this by raising issues with the impacted plugins and offering assistance.  We basically went down the list of projects with the topic netbox_plugins.


Given this is not a netbox_plugin, do you mind removing that topic from your project?  Thanks!
