### ISSUE TITLE
Displaying connections with < 1 Gbps

### ISSUE THREAD

**Issue by KaeGuD** [den-it/ntmap#8]
I'm currently visualizing our IT network wit ntmap and netbox as data source. SInce we have still some older devices we want to exchange, we first want to get an overview. One of our switches only supports up to 100 Mbps and as you can see in the picture, it wont display the connections with 100 Mbps. Only when there are multiple connection between to devices, it will display the enumeration of all these connections with a black dot.
How can I enable ntmap to display also connections lower than 1 Gbps?

![image](https://user-images.githubusercontent.com/88190890/127643029-fd74735d-0799-44f0-b2e8-0ed380609195.png)

**Comment by den-it** [comment]
Your issue is fixed in [release 0.7.1](https://github.com/den-it/ntmap/releases/tag/0.7.1). 

P.S. You can always add your own icons as 32x32 SVG images in www/img directory and you can change styles for your links in www/css/style.css file.

**Comment by KaeGuD** [comment]
Thank a lot for providing the update! I just installed it and it seem to work properply. I will check it in the next days and give you a better feedback.
