### ISSUE TITLE
Cables not showing up

### ISSUE THREAD

**Issue by joaolucasmacedo** [den-it/ntmap#9]
Hi. I've just installed NTmap on two different instances. Both running Python 3.8.
One with Netbox 2.11.12 and other Netbox 3.0.7.

Looks like everything is working as expected, but cables do not show up on any given topology map.

**Comment by NT5G** [comment]
I confirm. I have the same problem. Also Netbox 3.0.7 and Python 3.8.

**Comment by NT5G** [comment]
The problem also persists with the upgrade to netbox version 3.0.11 and Python version 3.8.2.
The ntmap version is 0.7.1.

**Comment by LHBL2003** [comment]
NTMAP v0.7.1
NETBOX v3.2.2
Python 3.10.4
PostgreSQL 14.2
Ubuntu 14.2

As described here, I was already able to find the errors for the current version, why ntmap does not show any devices.
https://github.com/den-it/ntmap/issues/14
But now I am also at the stage where no lines are displayed.

Switch100 is connected with 2 network cables to VMESX-FE01 (ilo and LAN)

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/46369917/169293801-26a4d273-b60d-421c-aea7-d116cad43181.png">


@den-it: Do you still support the ntmap? Some need your support here. THX

**Comment by marcucci-DAE** [comment]
Hi all, I have the same Problem I don't view any cable in the maps.

**Comment by reiters-it** [comment]
Hi all. I can confirm that no cables are shown with version

netbox 3.2.6
ntmap 0.7.1

![image](https://user-images.githubusercontent.com/99324507/178738257-f44278e2-f543-4496-bea1-12bbafb27e54.png)

**Comment by den-it** [comment]
It might be a problem with using variables in CSS file. CSS colors were changed in 0.8.0. Now they are defined explicitly and tey don't use variables. Can anyone confirm that it helped?

**Comment by LHBL2003** [comment]
![2022-09-18_22h21_47](https://user-images.githubusercontent.com/46369917/190927023-4734142c-055a-4aa7-9cf2-366bff8594cb.png)

Thanks for the fix in the other issue.
You seem to have fixed the connection problem as well.
In the current NetBox version it works again.
Many Thanks

**Comment by LHBL2003** [comment]
![2022-09-18_22h18_27](https://user-images.githubusercontent.com
/46369917/190927186-7506140c-16b8-41a0-94e1-45ec5bff88d4.png)

Thanks for the fix in the other issue.
You seem to have fixed the connection problem as well.
In the current NetBox version it works again.
Many Thanks

**Comment by LHBL2003** [comment]
![2022-09-18_22h18_27](https://user-images.githubusercontent.com/46369917/190927219-64af2a4c-f4e0-4627-be5c-f976fcdc2204.png)


Thanks for the fix in the other issue.
You seem to have fixed the connection problem as well.
In the current NetBox version it works again.
Many Thanks

I just haven't uploaded any icons to the name definition yet ;)

**Comment by den-it** [comment]
Tanks for the feedback. Closing the isse

**Comment by LHBL2003** [comment]
Currently NetBox Version 3.3.4

**Comment by den-it** [comment]
Yes. Ntmap 0.8.0 supports NetBox 3.3.4 as well.
